In [1]:
import torch

In [2]:
test = torch.empty((5,4))

In [3]:
test

tensor([[ 1.2383e-37,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 3.8200e+27,  4.5560e-41,  7.5086e+30,  4.5560e-41],
        [ 1.4013e-45,  2.6948e-09,  0.0000e+00,  0.0000e+00],
        [ 2.3906e-18,  4.5560e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [4]:
test[1,1] = 10

In [5]:
test

tensor([[ 1.2383e-37,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 3.8200e+27,  1.0000e+01,  7.5086e+30,  4.5560e-41],
        [ 1.4013e-45,  2.6948e-09,  0.0000e+00,  0.0000e+00],
        [ 2.3906e-18,  4.5560e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [6]:
test[1,1] = 909090909

In [7]:
test

tensor([[ 1.2383e-37,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 3.8200e+27,  9.0909e+08,  7.5086e+30,  4.5560e-41],
        [ 1.4013e-45,  2.6948e-09,  0.0000e+00,  0.0000e+00],
        [ 2.3906e-18,  4.5560e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])